Hepsi:Derle Calistir
Derle:
	g++ -I ./include -c ./src/Top.cpp -o ./lib/Top.o
	g++ -I ./include -c ./src/Kova.cpp -o ./lib/Kova.o
	g++ -I ./include -c ./src/KovaKontrol.cpp -o ./lib/KovaKontrol.o
	g++ -I ./include -c ./src/TestProgrami.cpp -o ./lib/TestProgrami.o
	g++ ./lib/Top.o ./lib/Kova.o ./lib/KovaKontrol.o ./lib/TestProgrami.o -o ./bin/TestProgrami.exe
Calistir:
	./bin/TestProgrami